Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 14
"GET /about/ HTTP/1.1" 200 11
D:\GB\HTML CSS\Django\hw1\hw1app\views.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 9
D:\GB\HTML CSS\Django\hw1\hw1app\views.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 16
"GET / HTTP/1.1" 200 16
"GET / HTTP/1.1" 200 16
D:\GB\HTML CSS\Django\hw1\hw1app\views.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 29
D:\GB\HTML CSS\Django\hw1\hw1app\views.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 23
"GET / HTTP/1.1" 200 23
D:\GB\HTML CSS\Django\hw1\hw1app\views.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 23
"GET / HTTP/1.1" 200 23
"GET / HTTP/1.1" 200 23
D:\GB\HTML CSS\Django\hw1\hw1app\views.py changed, reloading.
Watching for file changes with StatReloader
D:\GB\HTML CSS\Django\hw1\hw1app\views.py changed, reloading.
Watching for file changes with StatReloader
D:\GB\HTML CSS\Django\hw1\hw1app\views.py changed, reloading.
Watching for file changes with StatReloader
D:\GB\HTML CSS\Django\hw1\hw1app\views.py changed, reloading.
Watching for file changes with StatReloader
D:\GB\HTML CSS\Django\hw1\hw1app\views.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 90
D:\GB\HTML CSS\Django\hw1\hw1app\views.py changed, reloading.
Watching for file changes with StatReloader
D:\GB\HTML CSS\Django\hw1\hw1app\views.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 167
"GET / HTTP/1.1" 200 167
Not Found: /<function index at 0x0000024EE09BA840>index.html
"GET /%3Cfunction%20index%20at%200x0000024EE09BA840%3Eindex.html HTTP/1.1" 404 2568
D:\GB\HTML CSS\Django\hw1\hw1app\views.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 231
D:\GB\HTML CSS\Django\hw1\hw1app\views.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 234
D:\GB\HTML CSS\Django\hw1\hw1app\views.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 238
Not Found: /<function index at 0x0000021C8F44B100>index.html
"GET /%3Cfunction%20index%20at%200x0000021C8F44B100%3Eindex.html HTTP/1.1" 404 2568
D:\GB\HTML CSS\Django\hw1\hw1app\views.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /<function index at 0x0000021C8F44B100>index.html
"GET /%3Cfunction%20index%20at%200x0000021C8F44B100%3Eindex.html HTTP/1.1" 404 2568
Internal Server Error: /
Traceback (most recent call last):
  File "D:\GB\HTML CSS\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\HTML CSS\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\HTML CSS\Django\hw1\hw1app\views.py", line 10, in index
    f'<a href="{index()}index.html"> Главная </a>'\
                ^^^^^^^
TypeError: index() missing 1 required positional argument: 'request'
"GET / HTTP/1.1" 500 64564
Not Found: /docs
"GET /docs HTTP/1.1" 404 2414
Internal Server Error: /
Traceback (most recent call last):
  File "D:\GB\HTML CSS\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\HTML CSS\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\HTML CSS\Django\hw1\hw1app\views.py", line 10, in index
    f'<a href="{index()}index.html"> Главная </a>'\
                ^^^^^^^
TypeError: index() missing 1 required positional argument: 'request'
"GET / HTTP/1.1" 500 64701
D:\GB\HTML CSS\Django\hw1\hw1app\views.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 238
Not Found: /<function index at 0x0000020341E1B100>index.html
"GET /%3Cfunction%20index%20at%200x0000020341E1B100%3Eindex.html HTTP/1.1" 404 2568
D:\GB\HTML CSS\Django\hw1\hw1app\views.py changed, reloading.
Watching for file changes with StatReloader
D:\GB\HTML CSS\Django\hw1\hw1app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
D:\GB\HTML CSS\Django\hw1\hw1app\views.py changed, reloading.
Watching for file changes with StatReloader
D:\GB\HTML CSS\Django\hw1\hw1app\views.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 90
"GET /about/ HTTP/1.1" 200 84
D:\GB\HTML CSS\Django\hw1\hw1\settings.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 90
"GET / HTTP/1.1" 200 90
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2439
"GET / HTTP/1.1" 200 90
"GET /about HTTP/1.1" 301 0
"GET /about/ HTTP/1.1" 200 84
D:\GB\HTML CSS\Django\hw1\hw1\settings.py changed, reloading.
Watching for file changes with StatReloader
"GET /about/ HTTP/1.1" 200 61
D:\GB\HTML CSS\Django\hw1\hw1app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "D:\GB\HTML CSS\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\HTML CSS\Django\venv\Lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\HTML CSS\Django\venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "D:\GB\HTML CSS\Django\venv\Lib\site-packages\django\http\request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Bad Request: /
"GET / HTTP/1.1" 400 69416
D:\GB\HTML CSS\Django\hw1\hw1\settings.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 90
"GET /about/ HTTP/1.1" 200 84
"GET /about/ HTTP/1.1" 200 84
"GET / HTTP/1.1" 200 90
"GET / HTTP/1.1" 200 90
"GET / HTTP/1.1" 200 90
"GET / HTTP/1.1" 200 90
"GET /about/ HTTP/1.1" 200 84
Not Found: /cube
"GET /cube HTTP/1.1" 404 2414
Not Found: /number
"GET /number HTTP/1.1" 404 2420
Watching for file changes with StatReloader
Not Found: /les3/game/number/10
"GET /les3/game/number/10 HTTP/1.1" 404 2658
"GET /show_orders/3 HTTP/1.1" 301 0
"GET /show_orders/3/ HTTP/1.1" 200 78
"GET /show_orders/17/ HTTP/1.1" 200 51
"GET /show_orders/17/ HTTP/1.1" 200 51
"GET /show_orders/17/ HTTP/1.1" 200 51
"GET /show_orders/17/ HTTP/1.1" 200 51
"GET /show_orders/17/ HTTP/1.1" 200 85
D:\GB\HTML CSS\Django\hw1\hw1app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
D:\GB\HTML CSS\Django\hw1\hw1app\urls.py changed, reloading.
Watching for file changes with StatReloader
"GET /show_orders/17/ HTTP/1.1" 200 317
Not Found: /orders_total/week/
"GET /orders_total/week/ HTTP/1.1" 404 2877
Internal Server Error: /orders_total/17/week/
Traceback (most recent call last):
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\HTML CSS\Django\hw1\hw1app\views.py", line 43, in orders_total
    orders = Order.orders_by_time_delta(user_id, INTERVALS[interval])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\HTML CSS\Django\hw1\hw1app\models.py", line 34, in orders_by_time_delta
    today = timezone.now().date()
            ^^^^^^^^^^^^
AttributeError: type object 'datetime.timezone' has no attribute 'now'
"GET /orders_total/17/week/ HTTP/1.1" 500 69301
D:\GB\HTML CSS\Django\hw1\hw1app\models.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /orders_total/17/week/
Traceback (most recent call last):
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\HTML CSS\Django\hw1\hw1app\views.py", line 43, in orders_total
    orders = Order.orders_by_time_delta(user_id, INTERVALS[interval])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\HTML CSS\Django\hw1\hw1app\models.py", line 35, in orders_by_time_delta
    orders = Order.objects.filter(register_date__date__range=[today - time_delta, today], client_id=user_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\sql\query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\sql\query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\sql\query.py", line 1495, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\sql\query.py", line 1307, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\sql\query.py", line 1772, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'register_date' into field. Choices are: client, client_id, date_ordered, id, products, total_price
"GET /orders_total/17/week/ HTTP/1.1" 500 115900
D:\GB\HTML CSS\Django\hw1\hw1app\models.py changed, reloading.
Watching for file changes with StatReloader
D:\GB\HTML CSS\Django\hw1\hw1app\models.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 90
"GET / HTTP/1.1" 200 90
"GET /show_orders/17/ HTTP/1.1" 200 317
Not Found: /show
"GET /show HTTP/1.1" 404 2835
Internal Server Error: /orders_total/17/week/
Traceback (most recent call last):
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\HTML CSS\Django\hw1\hw1app\views.py", line 43, in orders_total
    orders = Order.orders_by_time_delta(user_id, INTERVALS[interval])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\HTML CSS\Django\hw1\hw1app\models.py", line 37, in orders_by_time_delta
    orders = Order.objects.filter(register_date__date__range=[today - time_delta, today], client_id=user_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\sql\query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\sql\query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\sql\query.py", line 1495, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\sql\query.py", line 1307, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\sql\query.py", line 1772, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'register_date' into field. Choices are: client, client_id, date_ordered, id, products, total_price
"GET /orders_total/17/week/ HTTP/1.1" 500 115763
Internal Server Error: /orders_total/17/week/
Traceback (most recent call last):
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\HTML CSS\Django\hw1\hw1app\views.py", line 43, in orders_total
    orders = Order.orders_by_time_delta(user_id, INTERVALS[interval])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\HTML CSS\Django\hw1\hw1app\models.py", line 37, in orders_by_time_delta
    orders = Order.objects.filter(register_date__date__range=[today - time_delta, today], client_id=user_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\sql\query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\sql\query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\sql\query.py", line 1495, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\sql\query.py", line 1307, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\sql\query.py", line 1772, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'register_date' into field. Choices are: client, client_id, date_ordered, id, products, total_price
"GET /orders_total/17/week/ HTTP/1.1" 500 115900
Internal Server Error: /orders_total/17/week/
Traceback (most recent call last):
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\HTML CSS\Django\hw1\hw1app\views.py", line 43, in orders_total
    orders = Order.orders_by_time_delta(user_id, INTERVALS[interval])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\HTML CSS\Django\hw1\hw1app\models.py", line 37, in orders_by_time_delta
    orders = Order.objects.filter(register_date__date__range=[today - time_delta, today], client_id=user_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\sql\query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\sql\query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\sql\query.py", line 1495, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\sql\query.py", line 1307, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dara3\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\sql\query.py", line 1772, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'register_date' into field. Choices are: client, client_id, date_ordered, id, products, total_price
"GET /orders_total/17/week/ HTTP/1.1" 500 115900
D:\GB\HTML CSS\Django\hw1\hw1app\models.py changed, reloading.
Watching for file changes with StatReloader
"GET /orders_total/17/week/ HTTP/1.1" 200 246
